#集群版配置
#com:
#  warape:
    #redis:
    #  pool:
    #    maxTotal: 100
    #    maxIdle: 10
    #    maxWaitMillis: 3000
    #  cluster:
    #    connectionTimeout: 3000
    #    soTimeout: 3000
    #    maxRedirections: 5
    #    jedisClusterNodes: 10.143.131.63:6391,10.143.131.63:6392,10.143.131.63:6393,10.143.131.63:6394,10.143.131.63:6395,10.143.131.63:6396
      #如果为多个集群 一次类推
      #cluster1:
      #  connectionTimeout:
      #  soTimeout:
      #  maxRedirections:
      #  jedisClusterNodes:
      #pool1:
      #  maxTotal: 100
      #  maxIdle: 10
      #  maxWaitMillis: 3000
  #单机版配置
com:
  warape:
   redis:
     standalone:
       client:
         host-name: 10.20.29.71
         port: 6379
       pool:
         max-total: 100
         max-idle: 10
         max-wait-millis: 1000



## 日志路径
logging:
  config: classpath:logback-spring-local.xml
