#集群版配置
com:
  warape:
    redis:
      pool:
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis: 3000
      cluster:
        connectTimeout: 2000
        readTimeout: 1000
        maxRedirections: 5
        jedisClusterNodes: 192.168.131.1:6379,192.168.131.2:6379,192.168.131.3:6379
      #如果为多个集群 一次类推
#      cluster1:
#        connectTimeout:
#        readTimeout:
#        maxRedirections:
#        jedisClusterNodes:
#      pool1:
#        maxTotal: 100
#        maxIdle: 10
#        maxWaitMillis: 3000



## 日志路径
logging:
  config: classpath:logback-spring-dev.xml
